# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatTestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for CatTestProject
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher' #'~> 3.13.1'

end
